<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<!DOCTYPE html>
<html>
<head>
<jsp:include page="includes.jsp" />
<title>Home</title>
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body>
	<div id="container">
		<jsp:include page="nav.jsp" />
		<div class="container">
			<h1>Biology Aligner</h1>
			<p>With biologyaligner.tech you can align DNA sequences and generate genetic trees. Read the tutorials to find out how to find DNA sequence data to use with this site, or to learn how the algorithms work. Request access to the site if you do not have access already.</p>
			<c:if test="${not empty user.username}">
				<p>Logged in as: ${user.username}</p>
			</c:if>
			<div id="myCarousel" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators">
					<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
					<li data-target="#myCarousel" data-slide-to="1"></li>
					<li data-target="#myCarousel" data-slide-to="2"></li>
				</ol>

				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="/assets/alignment.png" alt="Sequence Alignment">
						<div class="carousel-caption">
							<h3>Sequence Alignment</h3>
							<p>A multiple alignment of common animals.</p>
						</div>
					</div>

					<div class="item">
						<img src="/assets/homeTree.png" alt="Genetic Tree">
						<div class="carousel-caption">
							<h3>Genetic Tree</h3>
							<p>A genetic tree generated by a neighbor-joining algorithm.</p>
						</div>
					</div>

					<div class="item">
						<img src="/assets/ducks.jpg" alt="Ducks">
						<div class="carousel-caption">
							<h3>Ducks</h3>
							<p>Analyze the DNA of several species of animals.</p>
						</div>
					</div>


					<!-- Left and right controls -->
					<a class="left carousel-control" href="#myCarousel" role="button"
						data-slide="prev"> <span
						class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a> <a class="right carousel-control" href="#myCarousel" role="button"
						data-slide="next"> <span
						class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
		</div>
</body>
</html>